services:
  medispeak_backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV}
        BUNDLE_DEPLOYMENT: ${BUNDLE_DEPLOYMENT}
        BUNDLE_PATH: ${BUNDLE_PATH}
        BUNDLE_WITHOUT: ${BUNDLE_WITHOUT}
    container_name: medispeak_backend
    command: "bundle exec rails s -p ${BACKEND_PORT} -b '0.0.0.0'"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
      OPENAI_ORGANIZATION_ID: ${OPENAI_ORGANIZATION_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      PLUGIN_BASE_URL: ${PLUGIN_BASE_URL}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_REGION: ${MINIO_REGION}
      STORAGE_SERVICE: ${STORAGE_SERVICE}
    volumes:
      - .:/app:cached
    restart: unless-stopped
