[phases.setup]
# Set up the environment for Ruby and install system dependencies
commands = [
  "apt-get update -qq",
  "apt-get install --no-install-recommends -y curl libjemalloc2 libvips postgresql-client",
  "apt-get clean",
  "rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archives/*"
]

[phases.install]
# Install Ruby dependencies
commands = [
  "bundle install --jobs=4 --retry=3",
  "rm -rf ~/.bundle/ vendor/cache"
]

[phases.prebuild]
# Precompile gems and assets for production
commands = [
  "bundle exec bootsnap precompile --gemfile",
  "SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile"
]

[phases.build]
# Build phase to copy source code and set up the Rails environment
commands = [
  "cp -R . /app",
  "cd /app",
  "chown -R rails:rails db log storage tmp"
]

[phases.start]
# Command to run the application
commands = [
  "bundle exec rails server -p ${PORT:-3000} -b '0.0.0.0'"
]

[phases.default]
# Default environment variables
env = {
  "RAILS_ENV" = "production",
  "DB_HOST" = "${DB_HOST}",
  "DB_NAME" = "${DB_NAME}",
  "DB_USERNAME" = "${DB_USERNAME}",
  "DB_PASSWORD" = "${DB_PASSWORD}",
  "MINIO_ACCESS_KEY_ID" = "${MINIO_ACCESS_KEY_ID}",
  "MINIO_SECRET_ACCESS_KEY" = "${MINIO_SECRET_ACCESS_KEY}"
}
